apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google-oauth2
type: Opaque
data:
  GOOGLE_OAUTH2_CLIENT_ID: {{ .Values.google_oauth2_client_id | b64enc | quote }}
  GOOGLE_OAUTH2_CLIENT_SECRET: {{ .Values.google_oauth2_secret | b64enc | quote }}